### ISSUE TITLE
ส่งงาน Lab1 ครับ

### ISSUE THREAD

**Issue by aomnaherb** [03376814-computer-laboratory-1/week-01#2]
อาจารให้ส่งแบบนี้หรือ commit ในใหนครับ
หรือจะให้ผมส่งเป็นลิ้งค์แบบนี้เลย
[https://drive.google.com/file/d/1yEXFrYy9oJBzZx4n54u3f1MhBdvT44hR/view?usp=sharing](url)

**Comment by koson** [comment]
ขอปิด  issue นะครับ
คิดว่าคงสามารถส่งงานผ่าน pull request  กันได้หมดแล้ว
